#ifndef KD201EENUM_H
#define KD201EENUM_H

class KD201EEnum
{
public:
    enum DatapoolID{
        DP_VARIABLES_CONTROLLER = 0x00,
        DP_VARIABLES_SERIAL,
        DP_VARIABLES_SOFTWARE,
        DP_VARIABLES_TIME,
        DP_VARIABLES_PH,
        DP_VARIABLES_OC,
        DP_VARIABLES_TSS,
        DP_VARIABLES_FLOW,
        DP_VARIABLES_COD,

        DP_SETTINGS_PROVINCE_CODE = 0x20,   //QN
        DP_SETTINGS_COMPANY_NAME,           //VietHung
        DP_SETTINGS_COMPANY_CODE,           //VTHG
        DP_SETTINGS_STATION_NAME,           //Nuoc Thai Viet Hung
        DP_SETTINGS_STATION_CODE,           //NUOVTH
        DP_SETTINGS_STATION_TYPE,           //NuocThai
        DP_SETTINGS_HTML_SOURCE,            //192.168.1.200
        DP_SETTINGS_HTML_READ_INTERVAL,
        DP_SETTINGS_FTPSERVER_IP,
        DP_SETTINGS_FTPSERVER_PORT,
        DP_SETTINGS_FTPSERVER_USER,
        DP_SETTINGS_FTPSERVER_PASSWD,
        DP_SETTINGS_TIME_USINGHTML,

        DP_COMMON_HTML_CONNETED = 0x40,
        DP_COMMON_FTPSERVER_CONNETED,
        DP_COMMON_SETTINGS_STATE,
    };
};

#endif // KD201EENUM_H
