/****************************************************************************

    Copyright (C) 2018 by KingKong JSC
    File: hmievents.h
    Create: 23
    Author: Vuong Nguyen

 ****************************************************************************/

#ifndef HMIEVENTS_H
#define HMIEVENTS_H

#include <QObject>

class HMIEvents : public QObject
{
    Q_GADGET
    Q_ENUMS(HMIEvent)

public:
    enum HMIEvent {
        //button
        HMI_BUTTON_HOME,
        HMI_BUTTON_BACK,
        HMI_HOME_SETTING,
        HMI_HOME_WORK_MAIN,
        HMI_HOME_DATAVIEW,
        HMI_BUTTON_SAVE_SETTINGS_GENERAL,
        HMI_BUTTON_RELOAD_CONFIGURATION_FILE,
        HMI_BUTTON_DEVELOPER_SAVE_SCREENSHOT,
        HMI_BUTTON_WORK_MAIN_SEND,
        HMI_BUTTON_REQUEST_LOGIN,
        HMI_BUTTON_REQUEST_LOGOUT,
        HMI_BUTTON_REQUEST_LOGIN_TO_CONTINUE,
        HMI_BUTTON_WORK_SIMPLE_SEND,
        HMI_BUTTON_WORK_SWITCH_MODE,
        HMI_BUTTON_GENERATE_WORK_MAIN_TEXT,
        HMI_BUTTON_SET_DATE_TIME,
        HMI_REQUEST_GET_NETWORK_TIME,
        HMI_BUTTON_WORK_THUYVAN_SEND,
        HMI_BUTTON_WORK_HAIVAN_SEND,

        //keyboard
        HMI_KEYBOARD_DELETE,
        HMI_KEYBOARD_SAVE,

        //tab
        HMI_TAB_SELECT,

        //text input
        HMI_TEXTINPUT_FOCUS_CHANGED,
        HMI_TEXTINPUT_DONE_DEVICE_CODE,
        HMI_TEXTINPUT_DONE_DEVICE_NAME,
        HMI_TEXTINPUT_DONE_DEVICE_LOCATION,
        HMI_TEXTINPUT_DONE_TELEMETRY_GENERAL_SMSNOTIFY,
        HMI_TEXTINPUT_DONE_TELEMETRY_INTERNET_SERVER1,
        HMI_TEXTINPUT_DONE_TELEMETRY_INTERNET_SERVER2,

        //popup
        HMI_REQUEST_SHOW_COMMON_QN,
        HMI_REQUEST_HIDE_POPUP,
        HMI_REQUEST_HIDE_QN,

        //switch
        HMI_SWITCH_UPDATE_TIME_AUTOMATIC,

        //COMBOBOX
        HMI_COMBOBOX_TELEMETRY_SENDTYPE_CHANGED,
        HMI_COMBOBOX_TELEMETRY_CONTROLTYPE_CHANGED,
        HMI_COMBOBOX_TELEMETRY_NETWORKTYPE_CHANGED,
        HMI_COMBOBOX_TELEMETRY_PROTOCOLTYPE_CHANGED,
        HMI_COMBOBOX_DEVICETYPE_CHANGED,

        //spinbox
        HMI_SPINBOX_TELEMETRY_GENERAL_SENDINTERVAL,
        HMI_SPINBOX_SENSOR_INTERVAL,

        //request
        HMI_REQUEST_GET_CURRENT_USER_LOGIN_INFORMATION,
        HMI_REQUEST_GET_LOGIN_HISTORY,                      //user request
        HMI_REQUEST_DELETE_LOGIN_LIST,
        HMI_REQUEST_DELETE_DATAVIEW_LIST,
        HMI_REQUEST_SHOW_LOGIN,
        HMI_REQUEST_ADD_DELAY_EVENT,

        HMI_REQUEST_GET_ACCOUNT_LIST,
        HMI_REQUEST_DELETE_ACCOUNT_LIST,
        HMI_REQUEST_DB_SAVE_CHANGE_ACCOUNT,
        HMI_REQUEST_SHOW_DELETE_ACCOUNT_CONFIRM_POPUP,
        HMI_REQUEST_DB_DELETE_ACCOUNT,
        HMI_REQUEST_SHOW_CHANGE_PASSWORD_POPUP,
        HMI_REQUEST_DB_CHANGE_PASSWORD,
        HMI_REQUEST_SHOW_CREATE_ACCOUNT_POPUP,
        HMI_REQUEST_DB_CREATE_NEW_ACCOUNT,
        HMI_REQUEST_GET_DATAVIEW_LIST,
        HMI_REQUEST_DB_SAVE_KHITUONG,

        //
        HMI_RESPONSE_LOAD_SETTINGS_INI_FINISHED,
    };

    enum DbHandle {
        //db request
        DB_HANDLE_START = 0xA000,
        DB_RESPONSE_GET_LOGIN_HISTORY_FINISHED,                       //model request
        DB_RESPONSE_LOGIN_FINISHED,
        DB_RESPONSE_GET_ACCOUNT_LIST_FINISHED,
        DB_RESPONSE_GET_DATAVIEW_LIST_FINISHED,
        DB_HANDLE_END,
    };
};

#endif // HMIEVENTS_H
