#ifndef KD201EENUM_H
#define KD201EENUM_H

#include <QObject>

class Kd201eEnum : public QObject
{
    Q_OBJECT

public:
    enum DatapoolID{
        DP_VARIABLES_CONTROLLER = 0x00,
        DP_VARIABLES_SERIAL,
        DP_VARIABLES_SOFTWARE,
        DP_VARIABLES_TIME,
        DP_VARIABLES_PH,
        DP_VARIABLES_OC,
        DP_VARIABLES_TSS,
        DP_VARIABLES_FLOW,
        DP_VARIABLES_COD,

        DP_SETTINGS_STATIONNAME = 0x20,
        DP_SETTINGS_COMPANYNAME,
        DP_SETTINGS_STATIONTYPE,
        DP_SETTINGS_STATIONLINK,
        DP_SETTINGS_READ_INTERVAL,
        DP_SETTINGS_FTP_SERVERIP,
        DP_SETTINGS_FTP_USER,
        DP_SETTINGS_FTP_PSW,
        DP_SETTINGS_IS_USING_TIMEHTML,

        DP_COMMON_IS_STATION_CONNETED = 0x40,
        DP_COMMON_IS_FTP_CONNETED,
        DP_COMMON_SETTINGS_STATE,
        DP_COMMON_CURRENT_WORKINGFILE
    };
    Q_ENUM(DatapoolID)
};

#endif // KD201EENUM_H
