#ifndef DATAPOOLID_H
#define DATAPOOLID_H

class DPID
{
public:
    enum DPIDEnum {
        DP_THERMAL_TEMPERATURE,
        DP_THERMAL_TEMPERATURE_ALARM_NOTIFY,
        DP_SETTINGS_DEVICEID,
        DP_SETTINGS_DEVICENAME,
        DP_SETTINGS_DEVICETYPE,
        DP_SETTINGS_THRESOLD_MAXTEMP,
        DP_SETTINGS_THRESOLD_MINTEMP,
        DP_SETTINGS_VERIFYTIME,
        DP_SETTINGS_SERVERIP,
        DP_SETTINGS_SERVERPORT,
        DP_STATUS_SERVER_CONNECTED,
        DP_ALARM_FIRE,
        DP_SYSTEM_CPU_TEMPERATURE,
    };
};

#endif // DATAPOOLID_H
